### ISSUE TITLE
[BUG] pending friend requests in friendlist

### ISSUE THREAD

**Issue by Tom-jm03** [ValvePython/steam#404]
**Description**
When you loop trough your friendlist, the steam id's of friends that have not accepted the request are in there

**Steps to Reproduce the behavior**
define the steamfriendlist
```python
friendslist = SteamFriendlist(sc)
```
loop through the friendlist
```python
ids = []
for i in friendslist:
    ids.append(str(i.steam_id))
print(ids)
```
see that steam ids that are not yet in the friendlist are shown

**Expected behavior**
Only steamids of friends that are accepted are in the friendlist, not users where the request is pending

**Screenshots**

**Versions Report**
<details><summary>python -m steam.versions_report</summary>
(Run python -m steam.versions_report and paste the output below)

```yaml
steam: 1.3.0

Dependencies:
                 vdf: 3.4
            protobuf: 3.20.1
            requests: 2.26.0
          cachetools: 5.2.0
              gevent: 21.12.0
 gevent-eventemitter: 2.1
       pycryptodomex: 3.11.0
              enum34: Not Installed
       win-inet-pton: Not Installed

Python runtime:
          executable: /usr/bin/python3
             version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
            platform: linux

System info:
              system: Linux
             machine: x86_64
             release: 5.4.0
             version: #1 SMP Thu Apr 22 16:18:59 MSK 2021
```
</details>
