### ISSUE TITLE
[BUG]Can't login on latest version

### ISSUE THREAD

**Issue by Left024** [ValvePython/steam#422]
**Description**
Can't login on latest version

**Steps to Reproduce the behavior**
My repo to save steam game saves automatically: https://github.com/Left024/GameSaves
You can see all the codes

**Expected behavior**
client should login and no error print to console

**Screenshots**
![image](https://user-images.githubusercontent.com/20574903/209261015-dc031ea2-98a2-4d8d-b216-72c0278ae682.png)

**Versions Report**
<details><summary>python -m steam.versions_report</summary>
(Run python -m steam.versions_report and paste the output below)

```yaml
steam: 1.4.4

Dependencies:
                 vdf: 3.4
            protobuf: 3.20.3
            requests: 2.28.1
          cachetools: 5.2.0
              gevent: 22.10.2
 gevent-eventemitter: 2.1
       pycryptodomex: 3.16.0
              enum34: Not Installed
       win-inet-pton: Not Installed

Python runtime:
          executable: /opt/hostedtoolcache/Python/3.10.9/x64/bin/python3
             version: 3.10.9 (main, Dec  7 2022, 08:16:13) [GCC 11.3.0]
            platform: linux

System info:
              system: Linux
             machine: x86_64
             release: 5.[15](https://github.com/Left024/GameSaves/actions/runs/3762787975/jobs/6395795156#step:5:16).0-1024-azure
             version: #30-Ubuntu SMP Wed Nov [16](https://github.com/Left024/GameSaves/actions/runs/3762787975/jobs/6395795156#step:5:17) 23:37:59 UTC [20](https://github.com/Left024/GameSaves/actions/runs/3762787975/jobs/6395795156#step:5:21)[22](https://github.com/Left024/GameSaves/actions/runs/3762787975/jobs/6395795156#step:5:23)
```
</details>

**Comment by jethro1412** [comment]
Version 1.4.3 also affected

```
steam: 1.4.3

Dependencies:
                 vdf: 3.4
            protobuf: Not Installed
            requests: 2.25.1
          cachetools: 5.2.0
              gevent: Not Installed
 gevent-eventemitter: Not Installed
       pycryptodomex: 3.15.0
              enum34: Not Installed
       win-inet-pton: Not Installed

Python runtime:
          executable: /usr/bin/python3
             version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
            platform: linux

System info:
              system: Linux
             machine: x86_64
             release: 5.15.0-1019-aws
             version: #23-Ubuntu SMP Wed Aug 17 18:33:13 UTC 2022
```
