### ISSUE TITLE
[BUG] Error 29 DuplicateRequest when trying to add a new Authenticator

### ISSUE THREAD

**Issue by mx0c** [ValvePython/steam#429]
**Description**
When trying to add a new Authenticator to my Account SteamAuthenticator::add() returns error 29 DuplicateRequest.

**Steps to Reproduce the behavior**
```
wa = MobileWebAuth(user, pass)
wa.cli_login()
sa = SteamAuthenticator(backend=wa)
sa.add() 
```

**Expected behavior**
expected to receive SMS code

**Screenshots**

**Versions Report**
<details><summary>python -m steam.versions_report</summary>
(Run python -m steam.versions_report and paste the output below)

```yaml
steam: 1.4.4

Dependencies:
                 vdf: 3.4
            protobuf: 3.19.1
            requests: 2.28.2
          cachetools: 4.2.2
              gevent: 22.10.2
 gevent-eventemitter: 2.1
       pycryptodomex: 3.17
              enum34: Not Installed
       win-inet-pton: 1.1.0

Python runtime:
          executable: C:\Users\mariu\anaconda3\python.exe
             version: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
            platform: win32

System info:
              system: Windows
             machine: AMD64
             release: 10
             version: 10.0.22000
```
</details>
