### ISSUE TITLE
[BUG] Persistent login doesn't work

### ISSUE THREAD

**Issue by es3n1n** [ValvePython/steam#448]
**Description**
Not sure if its account related, or valve broke something, but once i set the credential path and authorize/relogin, nothing is getting stored within the credential location. Literally 0 files gets created when i run the `persistent_login` recipe.
upd: can confirm that it doesn't work on any other account i tried(3 accounts)

**Steps to Reproduce the behavior**
Run the [persistent login recipe](https://github.com/ValvePython/steam/blob/master/recipes/1.Login/persistent_login.py)

**Expected behavior**
A sentry file(i believe?) should be stored within the credential path once i authorize

**Versions Report**
<details><summary>python -m steam.versions_report</summary>

```yaml
steam: 1.4.4

Dependencies:
                 vdf: 3.4
            protobuf: 3.20.3
            requests: 2.31.0
          cachetools: 5.3.1
              gevent: 22.10.2
 gevent-eventemitter: 2.1
       pycryptodomex: 3.19.0
              enum34: Not Installed
       win-inet-pton: Not Installed

Python runtime:
          executable: C:\Users\retard\AppData\Local\pypoetry\Cache\virtualenvs\redacted-py3.7\Scripts\python.exe
             version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
            platform: win32

System info:
              system: Windows
             machine: AMD64
             release: 10
             version: 10.0.22621
```
</details>
