### ISSUE TITLE
[BUG] Unable to get_web_session anymore

### ISSUE THREAD

**Issue by csm10495** [ValvePython/steam#452]
**Description**
Recently I'm no longer able to get a web session via `get_web_session()`. It returns `None` every time.

**Steps to Reproduce the behavior**
```
client = SteamClient()
client.set_credential_location(CREDENTIALS_DIR)
login_result = client.cli_login(
    username=STEAM_ACCOUNT_NAME, password=STEAM_ACCOUNT_PASSWORD
)

client.idle()

# This will raise since get_web_session() is giving None
assert client.get_web_session()
```

**Expected behavior**
`get_web_session()` should give back a valid web session

**Screenshots**
N/A

**Versions Report**
<details><summary>python -m steam.versions_report</summary>
(Run python -m steam.versions_report and paste the output below)

```yaml
steam: 1.4.4

Dependencies:
                 vdf: 3.4
            protobuf: 3.20.3
            requests: 2.31.0
          cachetools: 5.2.0
              gevent: 22.10.2
 gevent-eventemitter: 2.1
       pycryptodomex: 3.15.0
              enum34: Not Installed
       win-inet-pton: Not Installed

Python runtime:
          executable: C:\Python3\python.exe
             version: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
            platform: win32

System info:
              system: Windows
             machine: AMD64
             release: 10
             version: 10.0.19045
```
</details>
