### ISSUE TITLE
[BUG] Sending messages to group.

### ISSUE THREAD

**Issue by kriki200** [ValvePython/steam#478]
**Description**

Idk if it is a bug. I want to send messages to a group, tried using the Documentations method, and I replaced the ID64 with a group ID64and got error 2. Is there even a way to send messages to a group? Nothing else besides Error 2 was in the output..

**Expected behavior**

Send a message to the group.

**Versions Report**
<details><summary>python -m steam.versions_report</summary>
(Run python -m steam.versions_report and paste the output below)

```yaml
steam: 1.4.4

Dependencies:
                 vdf: 3.4
            protobuf: 3.20.3
            requests: 2.32.3
          cachetools: 5.5.0
              gevent: 24.11.1
 gevent-eventemitter: 2.1
       pycryptodomex: 3.21.0
              enum34: Not Installed
       win-inet-pton: Not Installed

Python runtime:
          executable: /mnt/x/bin/python
             version: 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0]
            platform: linux

System info:
              system: Linux
             machine: x86_64
             release: 6.1.0-28-amd64
             version: #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22)
```
</details>
